vich_uploader:
    db_driver: orm

    mappings:
        restaurant_image:
            uri_prefix: /uploads/restaurants
            upload_destination: '%restaurants_images_directory%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
            delete_on_update: true
