<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260412163819 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE vendor_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(255) DEFAULT \'en_attente\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, processed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, processed_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_25E0B7F0A76ED395 ON vendor_request (user_id)');
        $this->addSql('CREATE INDEX IDX_25E0B7F02FFD4FD3 ON vendor_request (processed_by_id)');
        $this->addSql('ALTER TABLE vendor_request ADD CONSTRAINT FK_25E0B7F0A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vendor_request ADD CONSTRAINT FK_25E0B7F02FFD4FD3 FOREIGN KEY (processed_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE image ALTER file_name DROP NOT NULL');
        $this->addSql('ALTER TABLE "user" ADD notif_new_auctions BOOLEAN DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD notif_reminders BOOLEAN DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD notif_results BOOLEAN DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD notif_newsletter BOOLEAN DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE vendor_request DROP CONSTRAINT FK_25E0B7F0A76ED395');
        $this->addSql('ALTER TABLE vendor_request DROP CONSTRAINT FK_25E0B7F02FFD4FD3');
        $this->addSql('DROP TABLE vendor_request');
        $this->addSql('ALTER TABLE image ALTER file_name SET NOT NULL');
        $this->addSql('ALTER TABLE "user" DROP notif_new_auctions');
        $this->addSql('ALTER TABLE "user" DROP notif_reminders');
        $this->addSql('ALTER TABLE "user" DROP notif_results');
        $this->addSql('ALTER TABLE "user" DROP notif_newsletter');
    }
}
